### ISSUE TITLE
How to add self state? 

### ISSUE THREAD

**Issue by silkyland** [Wildhoney/Redecorate#2]
If I have blank state ( state = [] ), How to add user to state? 

```

import {apply, add} from 'redecorate';
let newUser = {id:1, name: "John Doe", age: 10};
...
const userReducer = (state=[], action ) => { 
...
case ADDUSER :
      return apply(state)(".??.", add(newUser));
      break;
...
}
```

Any help?

**Comment by Wildhoney** [comment]
Good question.

In that case I'd suggest you don't need `redecorate`. Could you not use the normal array spread?

```javascript
return [...state, 'another'];
```

**Comment by silkyland** [comment]
@Wildhoney  Thanks for your answer 👍

**Comment by Wildhoney** [comment]
👍 

`redecorate` is better suited to deeply nested objects &ndash; in the same way that [lenses](http://randycoulman.com/blog/2016/07/12/thinking-in-ramda-lenses/) are.

Lenses are a good alternative, although slightly more verbose. For example using [Ramda](http://ramdajs.com/docs/)'s lenses I can update the `name.firstName` prop quite easily like so:

```javascript
const model = { name: { firstName: null } };
const nameLens = lensPath(['name', 'firstName']);
const updatedModel = set(nameLens, 'Adam', model);
```

Where `updatedModel` is now `{ name: { firstName: 'Adam' } }`.

One of the advantages of lenses is that they're composable:

```javascript
const model = { name: { firstName: null, lastName: null } };
const firstNameLens = lensPath(['name', 'firstName']);
const lastNameLens = lensPath(['name', 'lastName']);
const update = compose(
    set(firstNameLens, 'Adam'),
    set(lastNameLens, 'Timberlake')
);
const updatedModel = update(model);
```

Where `updatedModel` is now `{ name: { firstName: 'Adam', lastName: 'Timberlake' } }`.
